In [1]:
import pandas as pd
df=pd.read_csv('/content/salaries.csv')
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [3]:
inputs= df.drop('salary_more_then_100k',axis='columns')
target=df.salary_more_then_100k

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [6]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])

In [7]:
inputs

       company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [9]:
inputs_n = inputs.drop(['company','job','degree'],axis='columns')

In [11]:

inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [12]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [13]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [14]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [16]:
model.score(inputs_n,target)

1.0

In [17]:
#Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?

model.predict([[2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [18]:
#Is salary of Google, Computer Engineer, Masters degree > 100 k ?

model.predict([[2,1,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

# Titanic dataset

In [26]:
df1=pd.read_csv('/content/titanic.csv')
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In this file using following columns build a model to predict if person would survive or not,

Pclass

Sex

Age

Fare

In [27]:
df1.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [28]:
df1.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [30]:
df1.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [32]:
inputs=df1.drop('Survived',axis='columns')
target=df1.Survived

In [54]:
df1[df1['Age'].isnull()]

     Survived  Pclass     Sex  Age     Fare
5           0       3    male  NaN   8.4583
17          1       2    male  NaN  13.0000
19          1       3  female  NaN   7.2250
26          0       3    male  NaN   7.2250
28          1       3  female  NaN   7.8792
..        ...     ...     ...  ...      ...
859         0       3    male  NaN   7.2292
863         0       3  female  NaN  69.5500
868         0       3    male  NaN   9.5000
878         0       3    male  NaN   7.8958
888         0       3  female  NaN  23.4500

[177 rows x 5 columns]

In [55]:
df1.groupby(['Sex']).Age.mean().round(0)

Sex
female    28.0
male      31.0
Name: Age, dtype: float64

In [56]:
inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [57]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [58]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [60]:
inputs.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [61]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split

In [84]:
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)

In [76]:
x_train.shape

(712, 4)

In [77]:
from sklearn.tree import DecisionTreeClassifier

In [78]:
model=DecisionTreeClassifier()

In [85]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [86]:
model.score(x_test,y_test)

0.8100558659217877

In [87]:
model.predict([[3,2,25,8]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [88]:
model.predict([[1,2,25,75]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [89]:
model.predict([[1,1,25,75]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [93]:
model.predict([[1,1,56,55]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])